### ISSUE TITLE
jellybean for the shell

### ISSUE THREAD

**Issue by ghost** [nanotech/jellybeans.vim#21]
Hi there, 

I would like to extend the use of jelly bean colorscheme to my shell environment. I use terminator (but not attached to it) which support 256 terminal color, with bash. I am not sure where to begin or if I should simply enter all the colors of the colorscheme in the bashrc or the setting of terminator. Any pointer would be great.

**Comment by nfarrar** [comment]
I'd *really* love to have jellybeans via base16. Still looks like it hasn't been ported. Thinking about working on it myself. It looks like base16-builder is the tool used to make new colorschemes - but I'm not seeing any documentation on how to use it. Is there a doc somewhere I'm missing?

**Comment by CJD14** [comment]
These aren't spectacular but they use the 8 colors defined in the ANSI color text listed above. I took those colors and brightened and softened them for the complimentary other 8. I then also kept the default normal and background colors. I made the extended palette on my own, but I used the web app called terminal.sexy to generate these three files. There is one for gnome terminal, termite, and xresource terminals. The gnome terminal one needs to be `chmod +x jellybean.gnome.sh && sh jellybean.gnome.sh` the other two you just copy to your config file. 

It looks pretty good, but I will adjust it and make a much better version later when I get a chance. 

https://drive.google.com/folder/d/0B2RIKQ9QDz7uYWpEMWRkbUxzUWs/edit

You can also take any of these files and import them on terminal.sexy site and see it in action, and can even export them to other formats like iTerm or Terminal.app and nearly 20 other formats.

**Comment by nfarrar** [comment]
@CJD14 Awesome, thanks. :) Gonna play with these today.

**Comment by meskarune** [comment]
This is what I came up with, maybe someone could find it useful: https://gist.github.com/meskarune/52703855720848586ec869adaeb1ed46
