### ISSUE TITLE
vim-powerline jellybeans theme

### ISSUE THREAD

**Issue by oryband** [nanotech/jellybeans.vim#26]
If [Vim-powerline](https://github.com/Lokaltog/vim-powerline/tree/develop/autoload/Powerline/Colorschemes) (or the [new powerline](https://github.com/Lokaltog/powerline/tree/develop/powerline/config_files/colorschemes)) will be color-themed to jellybeans, I'm gonna be so happy.

FYI, color themes are supported for this plugin.

**Comment by Javyre** [comment]
any updates on the situation?

**Comment by nanotech** [comment]
Just a little bit late to this issue... Airline has a [jellybeans port here](https://github.com/vim-airline/vim-airline-themes/blob/63b66df2851c0851df9e8018f62ed7208f3485de/autoload/airline/themes/jellybeans.vim). I don't use a plugin like Powerline or Airline myself, but anyone is free to port jellybeans to any program they like. There's also a [list of ports as a wiki page here](https://github.com/nanotech/jellybeans.vim/wiki/Ports).
