### ISSUE TITLE
Add `cterm`, `term', and `gui` to g:jellybeans_override

### ISSUE THREAD

**Issue by docwhat** [nanotech/jellybeans.vim#38]
Add the missing `highlight` attributes `cterm`, `term`, and `gui` to `g:jellybeans_override`.

You could also modify the override to look at attributes and set whatever the attributes that exist, looking for a `256` prefixed version for things that begin with `c.

This would work best when you have done #32 and #37.

This code may be helpful: [How to modify existing highlight group in vim?](http://stackoverflow.com/a/1333025/108857)

**Comment by nanotech** [comment]
`g:jellybeans_overrides` [will already set][1] both `gui` and `cterm` from an `attr` key, as in the [readme example][2]. Is that enough to suit your use case?

[1]: https://github.com/nanotech/jellybeans.vim/blob/f931895c20681684278aef2ffd810730b9c36ec3/colors/jellybeans.vim#L295
[2]: https://github.com/nanotech/jellybeans.vim/blob/f931895c20681684278aef2ffd810730b9c36ec3/README.markdown#custom-highlights

**Comment by docwhat** [comment]
Unless I read the code wrong it only works for the `fg` and `bg` versions.  Can you set `italic` or `bold` with those?

**Comment by nanotech** [comment]
Yep. Before:

![before](https://cloud.githubusercontent.com/assets/34699/6741382/9991a1dc-ce4c-11e4-8503-5f0cc1e305ca.png)

After:

![after](https://cloud.githubusercontent.com/assets/34699/6741386/9cf0f26a-ce4c-11e4-8288-e7ce7016c2f9.png)

**Comment by docwhat** [comment]
`attr`? Sigh, can't anything with terminals be simpler?
