### ISSUE TITLE
Out of the box transparency on common Linux terminals

### ISSUE THREAD

**Issue by nanotech** [nanotech/jellybeans.vim#39]
See:
- #34
- #28
- https://github.com/YourDearestEigenvalue/jellybeans.vim/commit/a9f49266a6f8a09740e7563901ad0f3144d76d58
- https://github.com/yeahnoob/jellybeans.vim/commit/072446ed7451c446eabd25798f1c6ba0d5654322
- https://github.com/corriander/jellybeans.vim/commit/f5469b35d5985dd833438c4d1c4b4412c48502f6
- https://github.com/bilalq/jellybeans.vim/commit/33d386e2e56c7f18648722cffec5bebd1bcf9832
- https://github.com/lkristjansen/jellybeans.vim/commit/3c854332dc9ac146dbb6f54f9588a31bb8d0c359
- [Vim color scheme overriding the background settings in Gnome Terminal](http://stackoverflow.com/questions/21572179/vim-color-scheme-overriding-the-background-settings-in-gnome-terminal)
- [Edit or remove background color for vim Jellybeans colorscheme](http://kaibun.net/blog/2010/09/04/edit-or-remove-background-color-for-vim-jellybeans-colorscheme/)

The solution is to stop setting a background color for Normal and friends.

**Comment by tb01110100** [comment]
Yeah, I've been struggling to get jellybeans to match the bg of the rest of my terminals. Thanks for these links.

**Comment by jgrar** [comment]
Here's a complete list of overrides if you don't want any background colours whatsoever:

https://gist.github.com/jgrar/e3d9213be8a6b1368614
