### ISSUE TITLE
fake transparency

### ISSUE THREAD

**Issue by r8b7xy** [nanotech/jellybeans.vim#40]
I'd love to see the fake transparency in jelly.
I know that It can be achieved with *overrides but maybe something like this will be  easier for users:

```vim
if (has("gui_running") && g:jellybeans_termtrans == 1)
    let g:jellybeans_background_color = "NONE"
else
    let g:jellybeans_background_color = "151515"
endif
```
EDIT:
when using overrides I have to change NonText as well and it breaks the vim-airline:
Broken:
![broken](http://i.imgur.com/Bgeqotl.png)
Normal:
![normal](http://i.imgur.com/i8mKrDr.png)
Code I've used:
```vim
let g:jellybeans_overrides = {
\   'Normal': { 'guifg': 'e8e8d3', 'guibg': '', 'ctermfg': 'White', 'ctermbg': '', 'attr': 'bold' },
\   'NonText': { 'guifg': '606060', 'guibg': '', 'ctermfg': '', 'ctermbg': 'Grey', 'attr': '' },
\}
```

**Comment by nanotech** [comment]
What do you mean by fake transparency? Is this is a dup of #39? That's odd that the status line is turning red though; NonText is all grey.
