### ISSUE TITLE
Loss of background color upon the latest update

### ISSUE THREAD

**Issue by brotatos** [nanotech/jellybeans.vim#47]
As pictured below, I no longer have the dark grey associated with the colorscheme. They gray background from my cursor is a result of `:set cursorline`.
![screen shot 2016-02-10 at 5 45 32 pm](https://cloud.githubusercontent.com/assets/1428272/12967693/2d10c61c-d01e-11e5-94b6-55ab78523454.png)

My vim-config is located [here](https://github.com/brotatos/vim-config/blob/master/vimrc). My current jellybeans.vim is on commit 2b423cf.

**Comment by kba** [comment]
https://github.com/nanotech/jellybeans.vim/commit/2b423cf7d9d300ea7dee70fac081aeb44c186007, the fix to #39 caused this. @nanotech 
Isn't there some way to keep the default at not setting a background but allow overriding it with a config option?

**Comment by nanotech** [comment]
Yeah, [new config option it is](https://github.com/nanotech/jellybeans.vim/commit/1e2cecee46ed3038dc53e61fad6db793ea2ab7fd). `let g:jellybeans_use_term_background_color = 1` restores the previous behavior, though it should auto-enable by default if you're using MacVim's vim. Thanks for the report!

**Comment by brotatos** [comment]
Should the new default option for jellybeans be transparent backgrounds? 

Most of the GUIs (or at least GUI related software) I've used in the past default to opaque backgrounds but provide the option of transparency.

**Comment by nanotech** [comment]
It's not that it defaults to transparent, but that it respects the terminal's transparency settings out of the box.

It would be nice if the theme could both set a background color and support transparency, but as far as I know that's not possible on gnome-terminal and Konsole. On Terminal.app and iTerm, it is possible, which is why the new setting is enabled by default there.

**Comment by jesusangelm** [comment]
same problem here on Linux.
jellybeans worked very well for many years, now is not working.
work well in gvim but not in vim terminal https://db.tt/Y2Md3l87
