### ISSUE TITLE
Can no longer hide tilde signs after the end of buffer in Neovim

### ISSUE THREAD

**Issue by meribold** [nanotech/jellybeans.vim#48]
As described [here](https://github.com/neovim/neovim/issues/2067), I'm hiding those tildes with

    hi EndOfBuffer ctermbg=bg ctermfg=bg guibg=bg guifg=bg
I think this was broken by https://github.com/nanotech/jellybeans.vim/commit/2b423cf7d9d300ea7dee70fac081aeb44c186007.  The error I get is:

    Error detected while processing function <SNR>1_hide_tildes:
    line    1:
    E420: BG color unknown

**Comment by nanotech** [comment]
Yeah, 2b423cf removed the background color by default. Maybe NeoVim should accept none as a value for bg, but since it doesn't, does this:

    hi EndOfBuffer ctermbg=none ctermfg=none guibg=none guifg=none

work?

**Comment by meribold** [comment]
No, it causes white tildes.

**Comment by nanotech** [comment]
Try adding

    let g:jellybeans_use_term_background_color = 1

to your .vimrc to get jellybeans to set a background color again, and use your original =bg highlight command.

**Comment by meribold** [comment]
Yes, that works. It also changes the background color back to the lighter shade used before 2b423cf7d9d300ea7dee70fac081aeb44c186007. Does jellybeans default to using the terminal's background color now?

**Comment by nanotech** [comment]
Yes, though I'm thinking of switching it back for backwards compatibility.

**Comment by meribold** [comment]
Thanks for your help!
