### ISSUE TITLE
Cursor column is nearly invisible with g:jellybeans_use_term_background_color = 1

### ISSUE THREAD

**Issue by brotatos** [nanotech/jellybeans.vim#49]
The color column defaults to a black vertical line as shown in the below picture. Is there a method to change the color?
<img width="874" alt="screen shot 2016-02-20 at 6 00 02 pm" src="https://cloud.githubusercontent.com/assets/1428272/13195982/00b45044-d7fc-11e5-807a-2524b7cfa631.png">

**Comment by nanotech** [comment]
Oops, this was a regression from 2b423cf. Fix incoming. Thanks!
