### ISSUE TITLE
Inverse behaviour of `jellybeans_use_term_background_color`

### ISSUE THREAD

**Issue by ikalnitsky** [nanotech/jellybeans.vim#51]
I use navy-like color for my terminal background. If I set

```vim
let g:jellybeans_use_term_background_color = 1
```

a black background is used in console Vim. If I set 

```vim
let g:jellybeans_use_term_background_color = 0
```

My terminal's background is used in console Vim.

Looks like we need to inverse that logic, since `jellybeans_use_term_background_color = 1` means **use term's background, not jellybeans**.

**Comment by nanotech** [comment]
Yeah, that was a poor naming choice. "Use term" here refers to setting (using) `ctermbg`, which is the opposite of using the terminal emulator background.

In any case, I've deprecated this option in favor of using overrides, and switched back to a default of setting a background color (bbd2cfc). I think this is more consistent with how other themes configure transparency. I've added the [new configuration for transparent terminals to the readme][1].

Thanks!

[1]: https://github.com/nanotech/jellybeans.vim#transparent-terminals
