### ISSUE TITLE
Enable bold fonts

### ISSUE THREAD

**Issue by DenniJensen** [nanotech/jellybeans.vim#54]
May I enable bold fonts in jellybeans?

**Comment by nanotech** [comment]
What do you mean? Jellybeans does use bold in a few places, but there's no options to enable or disable them.

**Comment by DenniJensen** [comment]
In `solarized` I may toggle bold font. I thought it could be possible in jellybeans too, but I figured out, jellybeans, like other colorschemes, have different sections for bold highlighting. 
I was totally wrong.
