### ISSUE TITLE
Terminal background overwrites scheme background

### ISSUE THREAD

**Issue by lyubenblagoev** [nanotech/jellybeans.vim#55]
I'm using Gnome Terminal with white background. Today I updated jellybeans and after the update when I open vim from the terminal the background is white and I can't set it unless I change terminal profile to one with black background.

This fixes the issue: 
```
:highlight Normal ctermbg=black
```

**Comment by nanotech** [comment]
Jellybeans now sets a background color by default again as of bbd2cfc.
