### ISSUE TITLE
Background is suddenly black

### ISSUE THREAD

**Issue by hobarrera** [nanotech/jellybeans.vim#57]
I recently updated to the latest version, and the background is suddenly black (was: #282828).  
I've bisected the issue to c5aa91982a9d9f3781f4c0b404f517e0629af647, but can't quite identify what resulted in this change.

I've temporarily worked around this by adding:
```
let g:jellybeans_overrides = {
\  'background': { 'guibg': '282828' },
\}
```

I believe it's possible that previous versions used my terminal's default background, while new versions explicitly set it to black.

**Comment by nanotech** [comment]
Yeah, bbd2cfc switched back to setting a background color (#151515). If you want to use your terminal's background color, you can use the [transparent terminal overrides from the readme][1]. Apologies for the config churn.

[1]: https://github.com/nanotech/jellybeans.vim#transparent-terminals

**Comment by hobarrera** [comment]
It's odd that bisecting pointed out a different commit (maybe I screwed up).

Anyway, maybe we can then document this and close the issue? Note that my terminal has no transparency (not even using a compositing WM), vim just used to pick up the terminal's default bg.

**Comment by nanotech** [comment]
Yes, good point. The `none` override can be used in any case where you want to use the default terminal background.

**Comment by hobarrera** [comment]
Thanks!
