### ISSUE TITLE
Need for higher contrast when displaying whitespace characters

### ISSUE THREAD

**Issue by graysky2** [nanotech/jellybeans.vim#62]
Using the theme, when I `:set list` the font for the end of line character and whitespaces is dark grey on black which is difficult to read.  Can you suggest a modification to allow these to be something more eye-catching light blue?  I am unsure where in the file I can define this myself.

**Comment by nanotech** [comment]
The `g:jellybeans_overrides` config will let you do this. Try adding this to your `.vimrc`:

```
let g:jellybeans_overrides = {
\    'SpecialKey': { 'guifg': '8fbfdc' },
\}
```

`8fbfdc` is just the blue used for `Structure` and `PreProc`; change it to whatever you like.

**Comment by graysky2** [comment]
Thanks... I ended up using this under the colorscheme lines:
```
"http://stackoverflow.com/questions/4998582/show-whitespace-characters-in-gvim
map <F4> :set list!<CR>
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
highlight SpecialKey term=standout ctermbg=yellow guibg=yellow
highlight RedundantSpaces term=standout ctermbg=Grey guibg=#ffddcc
```

**Comment by nanotech** [comment]
Yep, that works too, and will work with any colorscheme.
