### ISSUE TITLE
weird error on macvim 

### ISSUE THREAD

**Issue by marxst** [nanotech/jellybeans.vim#63]
When I use macvim in iTerm2 I get the following error with jellybeans as colorscheme enabled:

Error detected while processing function <SNR>17_X[6]..<SNR>17_rgb[7]..<SNR>17_color:
line    3:
E806: using Float as a String
E116: Invalid arguments for function float2nr(round(a:r - 8) / 10.0) + 232
E15: Invalid expression: float2nr(round(a:r - 8) / 10.0) + 232

Some time ago it worked just fine. 
How do I debug this?

**Comment by nanotech** [comment]
What is the output of `vim --version`? Also, try running vim with only Jellybeans loaded:

```sh
vim -u NONE -N -c 'set rtp+=~/.vim/bundle/jellybeans.vim' -c 'colorscheme jellybeans'
```

- `-u NONE` skips reading your `.vimrc`, to start with a default vim configuration.
- `-N` sets `nocompatible` so non-vi compatible features are enabled.
- `-c 'set rtp+=path/to/jellybeans-repo'` adds Jellybeans to the `runtimepath`, like a plugin manager would do. Omit this if you copied the colorscheme directly to `~/.vim/colors/`.
- `-c 'colorscheme jellybeans'` of course loads the color scheme.

**Comment by marxst** [comment]
I tried that all, nothing changed. Finally, after running through only the jellybeans.vim file with the vimscript debugger, I changed the line 
  return float2nr(round(a:r - 8) / 10.0) + 232
to
  return float2nr(round(a:r - 8) / 10) + 232

and the problem was gone.

However, on my Linux system this runs unchanged... Here on the Mac I use the latest macvim from homebrew in the latest iTerm2 on MacOSX 10.12.3 and a lot of plugins, and jellybeans also directly from the git repo.

**Comment by nanotech** [comment]
Interesting. Can you post the full output of `vim --version` so I can see what exact version you're running and what features your binary is compiled with?

**Comment by nanotech** [comment]
https://github.com/zhaocai/GoldenView.Vim/issues/21 has a similar error and seems to conclude that Vim's float parsing might depend on your locale.

**Comment by marxst** [comment]
```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 15 2017 15:45:10)
MacOS X (unix) version
Included patches: 1-329
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     -tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminfo
+browse          +fork()          +multi_lang      +termresponse
++builtin_terms  +fullscreen      -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +odbeditor       +toolbar
+clientserver    +insert_expand   +packages        +transparency
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
+file_in_path    +mouse_sgr       +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/Library/Frameworks -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/Library/Frameworks -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/opt/python/Frameworks -framework Python   -framework Ruby
```

iTerm2: Build 3.0.14
Python 2.7.13
macOS Sierra Version 10.12.3

What I do not see in my environment variables is any locale information except `LC_CTYPE=UTF-8`. But I will investigate further, this is really becoming interesting ;-)

**Comment by marxst** [comment]
Yeah...
`export LC_NUMERIC=en_US.UTF-8` lets me use `return float2nr(round(a:r - 8) / 10.0) + 232` without errors.
`export LC_NUMERIC=de_DE.UTF-8` breaks it. But changing the function to `return float2nr(round(a:r - 8) / 10,0) + 232` is not helping then ;-)
In my normal environment LC_NUMERIC is unset and this throws the error. Setting `export LANG=C` makes it work again.

**Comment by nanotech** [comment]
I was able to reproduce this by unsetting my `LANG` environment variable (or by changing the region in System Preferences to Germany and restarting my terminal. For some reason, only `en_*` regions set a `LANG` environment variable for me.) and setting `LC_NUMERIC=de_DE.UTF-8`.

```
$ unset LANG
$ LC_NUMERIC=de_DE.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim -u NONE -e -c "echo round(5.7)"
Error detected while processing command line:
E806: using Float as a String
E116: Invalid arguments for function round(5.7)
E15: Invalid expression: round(5.7) 
Entering Ex mode.  Type "visual" to go to Normal mode.
:q
$ /Applications/MacVim.app/Contents/MacOS/Vim -u NONE -e -c "echo round(5.7)"
6.0
Entering Ex mode.  Type "visual" to go to Normal mode.
:q
```

Dtracing for `setlocale` where the first argument is `LC_ALL` (0) or `LC_NUMERIC` (4),

```
$ sudo dtrace -n 'pid$target::setlocale:entry /arg0==0 || arg0==4/ { printf("setlocale(%d, \"%s\")", arg0, copyinstr(arg1)); ustack(); }' -c '/Applications/MacVim.app/Contents/MacOS/Vim -u NONE -e -c q'
dtrace: description 'pid$target::setlocale:entry ' matched 1 probe
dtrace: pid 15749 has exited
CPU     ID                    FUNCTION:NAME
  0  17120                  setlocale:entry setlocale(0, "")
              libsystem_c.dylib`setlocale
              Vim`common_init+0x82
              Vim`main+0xf9
              libdyld.dylib`start+0x1
              Vim`0x6

  0  17120                  setlocale:entry setlocale(4, "C")
              libsystem_c.dylib`setlocale
              Vim`common_init+0x93
              Vim`main+0xf9
              libdyld.dylib`start+0x1
              Vim`0x6

  0  17120                  setlocale:entry setlocale(0, "")
              libsystem_c.dylib`setlocale
              Vim`mac_lang_init+0x66
              Vim`set_init_1+0x7f1
              Vim`common_init+0x27b
              Vim`main+0xf9
              libdyld.dylib`start+0x1
              Vim`0x6
```

shows [Vim `setlocale`'ing `LC_NUMERIC` to "C"][0], [as intended][1] ([mailing list discussion][2]), and then the locale getting [reset by `mac_lang_init`][3].

If `LANG` is unset, `mac_lang_init` gets the system locale with the Apple API `LocaleRefGetPartString` (which seems to return the boot or perhaps login locale, not the currently selected region in System Preferences), sets `LANG`, and resets the locale using the updated environment. If the `LC_NUMERIC` environment variable is set, that [takes precedence over `LANG`'s default][4]. Setting `LANG` to anything at all will avoid `mac_lang_init` resetting `LC_NUMERIC`, and will still work because Vim `setlocale`s `LC_NUMERIC` itself.

So this looks like a Vim bug, and possibly an Apple bug if `LANG` is not being set for non-`en_*` regions. In the meantime, I'll work around this by using integer literal `10`. Thanks for the report!

[0]: https://github.com/vim/vim/blob/v8.0.0473/src/main.c#L1524-L1525
[1]: https://github.com/vim/vim/blob/v8.0.0473/src/eval.c#L5945-L5946
[2]: https://groups.google.com/d/msg/vim_dev/TjzlXEqDPmY/qGjAX55fYVoJ
[3]: https://github.com/vim/vim/blob/v8.0.0473/src/os_mac_conv.c#L576
[4]: http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html
