### ISSUE TITLE
Transparent Background with termguicolors

### ISSUE THREAD

**Issue by edwardreed81** [nanotech/jellybeans.vim#64]
Using the g:jellybean_overrides to set the background to transparent does not work in VIM 8.0 with termguicolors. It does seem to work in Neovim.

If I change

    let s:background_color="151515"

to

    let s:background_color="NONE"

It'll give me a transparent background in VIM 8.0, but that's clearly not the right way to do it.

Maybe relevant:
https://github.com/vim/vim/issues/981#issuecomment-242888470

**Comment by nanotech** [comment]
Looks like this might require a decent amount of refactoring to fix this for all highlights, so I've added a workaround for the common case of the background color for now in 41ecfb7cf4994dbb9977ea6fce3d8b1a84c13d9e. Let me know if this fixes the problem for you.

Thanks for the bug report, and for the pointer to the vim issue!

**Comment by edwardreed81** [comment]
The workaround in https://github.com/nanotech/jellybeans.vim/commit/2ca7d8a27072a8f449887179c3fee81cb00f8c18 does fix my issue. Thanks for the quick help!

**Comment by nanotech** [comment]
I looked at this again and it turns out the Vim issue only affects `Normal`, so the existing workaround is sufficient.
