### ISSUE TITLE
customize syntax color for my own keywords

### ISSUE THREAD

**Issue by shenghsi** [nanotech/jellybeans.vim#75]
I am trying to highlight my own keyword for Python in jellybeans.vim.
I added things like
syntax match mykey ...
syntax keyword mykey ..
and 
highlight mykey ctermfg=some color
It seems not working.
Am I not supposed to do things like this?

**Comment by nanotech** [comment]
IIRC `syntax` commands should go in `~/.vim/syntax/` files, not in colorscheme files. Adding `highlight` commands directly to jellybeans.vim should work, but they'll need to be added at the end of the file so they don't get overridden.
