### ISSUE TITLE
Transparent Terminals Override Does Not Work

### ISSUE THREAD

**Issue by robotdna** [nanotech/jellybeans.vim#76]
Hello,

I've added the transparent terminals override snippet as provided in the readme and it is still not transparent. Using terminal vim inside Konsole. Have I missed something?

**Comment by danjac** [comment]
I see the issue (using the exact code above, nvim + gnome terminal + termguicolors set). If I reload settings (:source ...init.vim) it works, but not on initial load.

**Comment by danjac** [comment]
Pasting the solution here: https://github.com/nanotech/jellybeans.vim/issues/73 at the end of the config did the trick:
`
if has('termguicolors')
  set termguicolors
  let g:jellybeans_overrides = {
  \    'background': { 'ctermbg': 'none', '256ctermbg': 'none', 'guibg': 'none' },
  \}
  colorscheme jellybeans
endif
`

**Comment by nanotech** [comment]
Closing as solved. Go ahead and re-open or start a new issue if you're still having trouble, @robotdna.

Just guessing, but it not working on the first load could be caused by having the `colorscheme jellybeans` line before the `let g:jellybeans_overrides` lines.
