### ISSUE TITLE
Support for vim-gitgutter new changes  for handling SignColumn

### ISSUE THREAD

**Issue by mechanicles** [nanotech/jellybeans.vim#79]
Recently **vim-gitgutter** added new changes https://github.com/airblade/vim-gitgutter/commit/afa4f2ddf0fecb37914ec37357636abb18013422. Could we handle this by default in jellybeans?

**Comment by nanotech** [comment]
Since vim-gitgutter is linking to the standard diff colors, there shouldn't be anything jellybeans needs to do. vim-gitgutter will just use the standard diff colors that jellybeans already defines.
